// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product_CRUD.Models;

namespace Product_CRUD.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220516192714_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Product_CRUD.Models.Entities.Category", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("CategoryId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CategoryName = "Drzewka owocowe"
                        },
                        new
                        {
                            Id = (short)2,
                            CategoryName = "Kwiaty"
                        },
                        new
                        {
                            Id = (short)3,
                            CategoryName = "Nasiona warzyw"
                        });
                });

            modelBuilder.Entity("Product_CRUD.Models.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductId");

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d61a7e77-5e74-4c2b-8c00-af3ddb381415"),
                            CategoryId = (short)1,
                            Name = "Wiśnia",
                            Price = 45.7806m
                        },
                        new
                        {
                            Id = new Guid("d8450d7f-4c25-4ada-87b6-4eeb70a96ca6"),
                            CategoryId = (short)1,
                            Name = "Jabłoń",
                            Price = 16.6911m
                        },
                        new
                        {
                            Id = new Guid("f6877b87-e139-403d-948e-10031ed670ad"),
                            CategoryId = (short)3,
                            Name = "Rzodkiewka",
                            Price = 8.8806m
                        },
                        new
                        {
                            Id = new Guid("d7b52148-9fe0-4fb2-88d5-82e6212b0584"),
                            CategoryId = (short)3,
                            Name = "Marchew",
                            Price = 1.5129m
                        },
                        new
                        {
                            Id = new Guid("67f36f59-e8d8-41ed-923e-2e23f1ded25d"),
                            CategoryId = (short)2,
                            Name = "Mak",
                            Price = 45.7806m
                        },
                        new
                        {
                            Id = new Guid("7d8af9fc-a577-4ffa-bed6-b0dbb53ea08c"),
                            CategoryId = (short)1,
                            Name = "Śliwka",
                            Price = 43.3329m
                        });
                });

            modelBuilder.Entity("Product_CRUD.Models.Entities.Product", b =>
                {
                    b.HasOne("Product_CRUD.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
